{{- if .Values.kong.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: matches-do-not-preserve-host
route:
  preserve_host: false
upstream:
  host_header: {{ include "matches.fullname" . }}.bets.svc
proxy:
  connect_timeout: 2000
  read_timeout: 2000
  write_timeout: 2000
{{end}}
