apiVersion: v1
kind: Service
metadata:
  name: {{ include "matches.fullname" . }}
  annotations:
    konghq.com/plugins: matches-logs,prometheus-matches
    ingress.kubernetes.io/service-upstream: "true"
  labels:
    {{- include "matches.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "matches.selectorLabels" . | nindent 4 }}
